GET http://localhost:5000/
###

POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "adliasu",
    "email":"hackingtopia0057@gmail.com",
    "password": "adliasu",
    "veryPassword": "adliasu"
}
###
#login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"hackingtopia0057@gmail.com",
    "password": "adliasu"
}

###
#me
GET http://localhost:5000/me

###

#logout
delete http://localhost:5000/logout

###
#get all user
GET http://localhost:5000/users
