GET http://localhost:5000/
###

POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "adliasu",
    "email":"hackingtopia0057@gmail.com",
    "password": "adliasu",
    "veryPassword": "adliasu"
}
###
#login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"muhamaddamar1812@gmail.com",
    "password": "mahiru123"
}

###
# #update user
# POST http://localhost:5000/me/update
# Content-Type: application/json

# {
#     "name": "mahiru",
#     "email":"mahiru@gmail.com",
#     "password": "mahiru123"
# }

###
#me
GET http://localhost:5000/me

###

#logout
delete http://localhost:5000/logout

###
#get all user
GET http://localhost:5000/users

###
#getOneUserScanner
GET http://localhost:5000/scanner/hackingtopia0057@gmail.com

###
#updateKehadiran
POST http://localhost:5000/scanner/hackingtopia0057@gmail.com
Content-Type: application/json

{
    "hadir": "hadir",
    "makanSiang": "",
    "Snack": "",
}
