GET http://localhost:5000/
###

POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "",
    "email":"",
    "password": "",
    "veryPassword": ""
}
###
#login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"hackingtopia0057@gmail.com",
    "password": "adliasu"
}

###
#me
GET http://localhost:5000/me

###

#logout
delete http://localhost:5000/logout

###
#getOneUserScanner
GET http://localhost:5000/scanner/example@gmail.com

###
#updateKehadiran
POST http://localhost:5000/scanner/example@gmail.com
Content-Type: application/json

{
    "hadir": "",
    "makanSiang": "",
    "Snack": "",
}

###
#hitung role
POST http://localhost:5000/test
Content-Type: application/json

{
    "role": ""
}

###
#get all user for admin
GET http://localhost:5000/admin

###
#search data user
POST http://localhost:5000/admin
Content-Type: application/json

{
  "keyword": ""
}

###
#deleted
DELETE http://localhost:5000/admin/deleted/id

###
#update data diri
POST http://localhost:5000/me/update
Content-Type: application/json

{
  "name": "damar aja"
}